server:
  port: 5555

spring:
  application:
    name: api-gateway

#routes to serviceId
zuul:
  routes:
    api-a:
      path: /api-a/**
    api-b:
      serviceId : service-A
    api-b:
      path: /api-b/**
    api-b:
      serviceId: service-B

    api-a-url:
      path: /api-a-url/**

    api-a-url:
      url:  http://localhost:2222/


eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:1111/eureka/


